# Generated by Django 4.2.11 on 2024-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100)),
                ('response_data', models.JSONField()),
                ('time_taken', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.IntegerField()),
                ('number_of_vehicles', models.IntegerField()),
                ('routes', models.TextField()),
                ('maximum_distance', models.IntegerField()),
            ],
        ),
    ]
