# Generated by Django 4.2.11 on 2024-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField(help_text='Unique identifier for the submission')),
                ('problem_name', models.CharField(help_text='Name of the problem solved', max_length=100)),
                ('response_data', models.JSONField(help_text='The response data from the computation')),
                ('time_taken', models.FloatField(help_text='Time taken to solve the problem in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the result was recorded')),
            ],
        ),
        migrations.CreateModel(
            name='VRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.IntegerField()),
                ('number_of_vehicles', models.IntegerField()),
                ('routes', models.TextField()),
                ('maximum_distance', models.IntegerField()),
            ],
        ),
    ]
