# Generated by Django 4.2.11 on 2024-05-27 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='The user ID associated with this balance', unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='The current credit balance of the user', max_digits=10)),
            ],
            options={
                'verbose_name': 'User Credit Balance',
                'verbose_name_plural': 'User Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.DecimalField(decimal_places=2, help_text='Amount of credits purchased', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the transaction was created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
