# Generated by Django 4.2.11 on 2024-05-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolverModel',
            fields=[
                ('model_id', models.AutoField(help_text='Unique identifier for the solver model', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the solver model', max_length=200)),
                ('name', models.CharField(help_text='Name of the problem, as it is written in the url', max_length=200)),
                ('notes', models.TextField(help_text='Notes about the solver model')),
            ],
            options={
                'verbose_name': 'Solver Model',
                'verbose_name_plural': 'Solver Models',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('submission_id', models.AutoField(help_text='Unique identifier for the submission', primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='The username of the user involved in the problem', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the metadata was recorded')),
                ('credit_cost', models.DecimalField(decimal_places=2, help_text='The cost in credits for solving the problem', max_digits=10)),
                ('is_executed', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=True)),
                ('model_id', models.ForeignKey(help_text='Reference to the Solver Model for problem type', on_delete=django.db.models.deletion.CASCADE, to='problemService.solvermodel')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(blank=True, help_text='Input file for the problem', null=True, upload_to='inputs/')),
                ('input_data', models.JSONField(blank=True, help_text='Additional input data for the problem', null=True)),
                ('metadata', models.ForeignKey(help_text='Reference to the Metadata', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='problemService.metadata')),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
            },
        ),
    ]
